// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATUNvOJDcK0DhQd1b6GoSTETEp4NrIUiI',
    appId: '1:891802212780:web:48fafaf80755bac3e88209',
    messagingSenderId: '891802212780',
    projectId: 'phone-authentication-1a167',
    authDomain: 'phone-authentication-1a167.firebaseapp.com',
    storageBucket: 'phone-authentication-1a167.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-SgkomsXAjsGTBOykj9vH8TvzGGDYJqw',
    appId: '1:891802212780:android:bcf47ef6b3065b07e88209',
    messagingSenderId: '891802212780',
    projectId: 'phone-authentication-1a167',
    storageBucket: 'phone-authentication-1a167.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD25fvBmcVCcAY5-009Xjqbr_30dDEpmcU',
    appId: '1:891802212780:ios:290d13ed6f4a1984e88209',
    messagingSenderId: '891802212780',
    projectId: 'phone-authentication-1a167',
    storageBucket: 'phone-authentication-1a167.appspot.com',
    androidClientId: '891802212780-g0j6olcg5aut6hboie2esuk4di4i6u8a.apps.googleusercontent.com',
    iosClientId: '891802212780-ehs00hhu54g7lnk7t3san4po94tffd3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD25fvBmcVCcAY5-009Xjqbr_30dDEpmcU',
    appId: '1:891802212780:ios:290d13ed6f4a1984e88209',
    messagingSenderId: '891802212780',
    projectId: 'phone-authentication-1a167',
    storageBucket: 'phone-authentication-1a167.appspot.com',
    androidClientId: '891802212780-g0j6olcg5aut6hboie2esuk4di4i6u8a.apps.googleusercontent.com',
    iosClientId: '891802212780-ehs00hhu54g7lnk7t3san4po94tffd3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneAuth',
  );
}
